version: '2'
services:

  mombot:
    env_file:
      variables.env
    build:
      context: .
      dockerfile: Dockerfile
    image: mombot:local-latest
    ports:
      - 80:80
    volumes:
        - ./:/opt/
    command: nodemon
