version: '2'
services:

  flaviobot:
    env_file:
      variables.env
    build:
      context: .
      dockerfile: Dockerfile
    image: flaviobot:local-latest
    ports:
      - 80:80
    volumes:
        - ./:/opt/
    command: nodemon
